/*!
  prairiedog is a tool for providing kernel boot related support in Bottlerocket.

It does the following:
  - _digs_ to find the active boot partition and mounts it in /boot
  - loads the crash kernel from /boot
  - creates memory dumps when the kernel panics
  - generates kernel boot config from settings
  - generates settings from the existing kernel boot config file

*/

#[macro_use]
extern crate log;

use crate::bootconfig::{generate_boot_config, generate_boot_settings, is_reboot_required};
use crate::error::Result;
use argh::FromArgs;
use simplelog::{Config as LogConfig, LevelFilter, SimpleLogger, WriteLogger};
use snafu::{ensure, ResultExt};
use std::env;
use std::ffi::OsStr;
use std::fs::{self, File};
use std::path::{Path, PathBuf};
use std::process::{self, Command};
use std::thread;
use std::time::Duration;

mod bootconfig;
mod error;
mod initrd;

// Prairie dog config path
const DEFAULT_CONFIG_FILE: &str = "/etc/prairiedog.toml";
// Kdump related binary paths
const MAKEDUMPFILE_PATH: &str = "/sbin/makedumpfile";
const KEXEC_PATH: &str = "/sbin/kexec";

// Mount points created prairiedog
const BOOT_MOUNT_PATH: &str = "/boot";

// Filesystems used for the boot partition. GRUB images use ext4; UKI images use FAT, since
// systemd-boot has to be able to read the partition from the firmware.
const BOOT_FS_EXT4: &str = "ext4";
const BOOT_FS_VFAT: &str = "vfat";

// Mount options for the FAT boot partition on UKI images.
//
// FAT stores no ownership or permission bits, so they are set for the whole filesystem: only root
// may read it. `shortname=winnt` and `iocharset=iso8859-1` keep name handling predictable.
//
// FAT also stores no extended attributes, so SELinux labels can't live on the filesystem, and
// there is no fcontext rule for /boot to fall back on because it is a separate filesystem. The
// label therefore has to be applied at mount time.
const VFAT_MOUNT_DATA: &str =
    "umask=0077,shortname=winnt,iocharset=iso8859-1,context=system_u:object_r:os_t:s0";

// Set by prepare-boot.service from /usr/share/bottlerocket/image-format.env. Only consulted when
// the partition table doesn't tell us which boot layout the image uses.
const UKI_IMAGE_ENV: &str = "UKI_IMAGE";

// Files generated by prairiedog
const KDUMP_LOGS_PATH: &str = "/var/log/kdump";
const LOG_FILE: &str = "prairiedog.log";
const DMESG_DUMP_FILE: &str = "dmesg.log";
const KDUMP_FILE: &str = "vmcore.dump";

// Stores how much memory was allocated for the crash kernel
const KEXEC_CRASH_SIZE: &str = "/sys/kernel/kexec_crash_size";
// Enables/disables the kexec_load/kexec_file_load syscalls
const KEXEC_LOAD_DISABLED: &str = "/proc/sys/kernel/kexec_load_disabled";
// Crash kernel additional CMD line parameters
const KEXEC_CMD_LINE: &str = "maxcpus=1 systemd.unit='capture-kernel-dump.service' nr_cpus=1 \
                              swiotlb=noforce cma=0 reset_devices cgroup_disable=memory \
                              udev.children-max=2 panic=10 nvme_core.admin_timeout=20 swiotlb=1";

// Used to pass None to nix::mount::mount
const NONE: Option<&'static [u8]> = None;

/// Stores arguments
#[derive(FromArgs, PartialEq, Debug)]
struct Args {
    #[argh(option, default = "LevelFilter::Info", short = 'l')]
    /// log-level trace|debug|info|warn|error
    log_level: LevelFilter,
    #[argh(option, default = "PathBuf::from(DEFAULT_CONFIG_FILE)", short = 'c')]
    /// config-path to provide alternate config file path
    config_path: PathBuf,
    #[argh(subcommand)]
    subcommand: Subcommand,
}

/// Stores the subcommand to be executed
#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand)]
enum Subcommand {
    PrepareBoot(PrepareBootArgs),
    CaptureDump(CaptureDumpArgs),
    LoadCrashKernel(LoadCrashKernelArgs),
    GenerateBootConfig(GenerateBootConfigArgs),
    GenerateBootSettings(GenerateBootSettingsArgs),
    RebootIfRequired(RebootIfRequiredArgs),
}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "prepare-boot")]
/// Mounts the active boot partition on /boot
struct PrepareBootArgs {}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "capture-dump")]
/// Captures the dmesg and kdump dumps from the memory image
struct CaptureDumpArgs {}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "load-crash-kernel")]
/// Loads the crash kernel with kexec
struct LoadCrashKernelArgs {}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "generate-boot-config")]
/// Generate boot configuration from settings
pub(crate) struct GenerateBootConfigArgs {}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "generate-boot-settings")]
/// Generate boot settings from existing boot configuration
pub(crate) struct GenerateBootSettingsArgs {}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "reboot-if-required")]
/// Reboot the host if reboot-to-reconcile is set and the boot settings changed
struct RebootIfRequiredArgs {}

/// Wrapper around process::Command that adds error checking.
fn command<I, S>(bin_path: &str, args: I) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<OsStr>,
{
    let mut command = Command::new(bin_path);
    command.args(args);
    let output = command
        .output()
        .context(error::ExecutionFailureSnafu { command })?;

    trace!("stdout: {}", String::from_utf8_lossy(&output.stdout));
    trace!("stderr: {}", String::from_utf8_lossy(&output.stderr));

    ensure!(
        output.status.success(),
        error::CommandFailureSnafu { bin_path, output }
    );

    Ok(())
}

/// Dumps the memory image in `/proc/vmcore`, which is created when the kernel crashes
fn capture_dump() -> Result<()> {
    let kdump_file_path = format!("{KDUMP_LOGS_PATH}/{KDUMP_FILE}");
    let dmesg_file_path = format!("{KDUMP_LOGS_PATH}/{DMESG_DUMP_FILE}");

    // Delete previous dumps, if they exist
    if Path::new(&kdump_file_path).exists() {
        info!("Deleting existing memory dump");
        fs::remove_file(&kdump_file_path).context(error::RemoveFileSnafu {
            path: &kdump_file_path,
        })?;
    }

    if Path::new(&dmesg_file_path).exists() {
        info!("Deleting existing dmesg dump");
        fs::remove_file(&dmesg_file_path).context(error::RemoveFileSnafu {
            path: &dmesg_file_path,
        })?;
    }

    info!("Generating dmesg dump");
    // --dump-dmesg generates a dump with only dmesg logs
    command(
        MAKEDUMPFILE_PATH,
        [
            "--dump-dmesg",
            "--message-level",
            "4",
            "/proc/vmcore",
            dmesg_file_path.as_ref(),
        ],
    )?;

    info!("Generating memory dump");
    // Extract kdump-compressed dump file, without empty pages, using
    // zlib compression
    command(
        MAKEDUMPFILE_PATH,
        [
            "-c",
            "--message-level",
            "4",
            "-d",
            "31",
            "/proc/vmcore",
            kdump_file_path.as_ref(),
        ],
    )?;

    Ok(())
}

/// What to mount on `BOOT_MOUNT_PATH`, once the OS disk and the image format have been consulted.
#[derive(Debug, PartialEq)]
enum BootAction {
    /// Mount this XBOOTLDR partition as FAT: the partition table says this is a UKI image.
    MountXbootldr(PathBuf),
    /// Mount the boot partition of the active partition set as ext4: this is a GRUB image.
    MountActiveSet,
    /// This is a UKI image, but it has no XBOOTLDR partition, so there is nothing to mount.
    MissingXbootldr,
}

/// Decides what to mount from the XBOOTLDR partition found on the OS disk, if any, and the image
/// format recorded at build time.
///
/// The partition table is the primary signal, so `uki_image` is only consulted when the disk has no
/// XBOOTLDR partition - either because it has none or because the scan for one failed.
fn boot_action(xbootldr: Option<PathBuf>, uki_image: impl FnOnce() -> bool) -> BootAction {
    match xbootldr {
        Some(boot_partition_path) => BootAction::MountXbootldr(boot_partition_path),
        // A UKI image boots from the XBOOTLDR partition and has no A/B partition sets to fall back
        // on, so a missing partition means /boot can never be populated. Fail loudly instead of
        // leaving it unmounted, which would silently break everything that reads /boot.
        None if uki_image() => BootAction::MissingXbootldr,
        None => BootAction::MountActiveSet,
    }
}

// Mounts the boot partition of the active partition set, or the XBOOTLDR partition on UKI images
fn prepare_boot() -> Result<()> {
    // The partition table is the primary signal for which boot layout this image uses: UKI images
    // tag their boot partition with the XBOOTLDR type GUID and format it as FAT, while GRUB images
    // keep an ext4 boot partition in each A/B partition set. Reading the GPT means we don't have to
    // trust anything the build recorded in the root filesystem.
    let (xbootldr, scan_error) = match signpost::xbootldr_partition() {
        Ok(partition) => (partition, None),
        Err(e) => {
            // Not fatal by itself: a GRUB image still has the boot partition of its active
            // partition set to mount. Log it here so the cause reaches the journal on every
            // path, and hold on to it so a UKI image can report it as the underlying cause
            // rather than claiming the partition is absent.
            warn!("Unable to scan the OS disk for an XBOOTLDR partition: {e}");
            (None, Some(e))
        }
    };

    match boot_action(xbootldr, uki_image_from_env) {
        BootAction::MountXbootldr(boot_partition_path) => {
            info!(
                "Found XBOOTLDR partition {} on the OS disk, so this is a UKI image",
                boot_partition_path.display()
            );
            mount_boot_partition(&boot_partition_path, BOOT_FS_VFAT, Some(VFAT_MOUNT_DATA))
        }

        BootAction::MissingXbootldr => match scan_error {
            // The disk may well have an XBOOTLDR partition that we were unable to see, so report
            // why the scan failed instead of reporting the partition as absent.
            Some(source) => Err(source).context(error::ScanForXbootldrPartitionSnafu),
            None => error::MissingXbootldrPartitionSnafu.fail(),
        },

        BootAction::MountActiveSet => {
            info!("No XBOOTLDR partition found on the OS disk; using the boot partition of the active partition set");
            // Get the current partitions state
            let state = signpost::State::load().context(error::LoadStateSnafu)?;

            mount_boot_partition(&state.active_set().boot, BOOT_FS_EXT4, None)
        }
    }
}

/// Reports whether the image format environment says this is a UKI image.
fn uki_image_from_env() -> bool {
    match env::var(UKI_IMAGE_ENV) {
        Ok(value) => {
            info!("{UKI_IMAGE_ENV} is set to '{value}' in the environment");
            value.trim() == "true"
        }
        Err(_) => {
            info!(
                "{UKI_IMAGE_ENV} is not set in the environment; assuming this is not a UKI image"
            );
            false
        }
    }
}

/// Mounts `partition_path` read-only on `BOOT_MOUNT_PATH`, then makes the mount private.
fn mount_boot_partition(partition_path: &Path, fstype: &str, data: Option<&str>) -> Result<()> {
    let flags = nix::mount::MsFlags::MS_NOSUID
        | nix::mount::MsFlags::MS_NODEV
        | nix::mount::MsFlags::MS_NOEXEC
        | nix::mount::MsFlags::MS_NOATIME
        | nix::mount::MsFlags::MS_RDONLY;

    info!(
        "Mounting {} in {} as {}",
        partition_path.display(),
        BOOT_MOUNT_PATH,
        fstype
    );
    // Mount the boot partition in /boot
    nix::mount::mount(
        Some(partition_path),
        BOOT_MOUNT_PATH,
        Some(fstype),
        flags,
        data.map(str::as_bytes),
    )
    .context(error::MountSnafu {
        path: BOOT_MOUNT_PATH,
    })?;

    // Make the mount point private so new mount namespaces don't have
    // access to it. This has to be set as a different call otherwise
    // the mount syscall returns `EINVAL`
    nix::mount::mount(
        NONE,
        BOOT_MOUNT_PATH,
        NONE,
        nix::mount::MsFlags::MS_PRIVATE,
        NONE,
    )
    .context(error::SetupMountSnafu {
        path: BOOT_MOUNT_PATH,
    })?;

    Ok(())
}

/// Loads the crash kernel using kexec-tools
fn load_crash_kernel() -> Result<()> {
    let kexec_crash_size_path = Path::new(KEXEC_CRASH_SIZE);
    let kexec_crash_size = fs::read(kexec_crash_size_path).context(error::ReadFileSnafu {
        path: kexec_crash_size_path,
    })?;
    let memory_allocated = String::from_utf8_lossy(&kexec_crash_size);

    // We provide a more useful message when no memory was reserved for the crash kernel. Exit
    // gracefully since the user could have decided to use a tiny host, and the system shouldn't be
    // in "degraded" state
    if memory_allocated.trim() == "0" {
        info!("No memory assigned for crash kernel. If you want to use kdump, please make sure the host has at least 2GB of memory");
        return Ok(());
    }

    let kexec_load_disabled_path = Path::new(KEXEC_LOAD_DISABLED);
    let kexec_load_disabled_value =
        fs::read(kexec_load_disabled_path).context(error::ReadFileSnafu {
            path: kexec_load_disabled_path,
        })?;
    let kexec_load_disabled = String::from_utf8_lossy(&kexec_load_disabled_value).trim() == "1";

    // We provide a more useful message when `kexec_load_disabled` is set to 1
    if kexec_load_disabled {
        return error::KexecLoadDisabledSnafu.fail();
    }

    // Conditionally add `irqpoll` depending on the architecture
    let kexec_cmd_line = if cfg!(target_arch = "x86_64") {
        String::from(KEXEC_CMD_LINE) + " irqpoll"
    } else {
        String::from(KEXEC_CMD_LINE)
    };

    info!("Loading crash kernel");
    // Load the panic kernel from `BOOT_MOUNT_PATH`, using the kexec_file_load syscall.
    // We reuse the cmd line in /proc/cmdline to boot the crash kernel, and we start
    // a specific systemd service instead of the default target.
    command(
        KEXEC_PATH,
        [
            "-ps",
            "--reuse-cmdline",
            "--append",
            kexec_cmd_line.as_ref(),
            format!("{BOOT_MOUNT_PATH}/vmlinuz").as_ref(),
        ],
    )?;

    info!("Crash kernel loaded");
    Ok(())
}

fn reboot_if_required<P>(config_path: P) -> Result<()>
where
    P: AsRef<Path>,
{
    if is_reboot_required(config_path)? {
        info!("Boot settings changed and require a reboot to take effect. Initiating reboot...");
        command("/usr/bin/systemctl", ["reboot"])?;
        // The "systemctl reboot" process will not block until the host does
        // reboot, but return as soon as the request either failed or the job
        // to start the systemd reboot.target and its dependencies have been
        // enqueued. As the shutdown.target that is being pulled in conflicts
        // with most anything else, the other jobs needed to boot the host
        // will be cancelled and the boot will not proceed.
        //
        // The above is subtle, so slowly spin here until systemd kills this
        // prairiedog process as part of the host shutting down by sending it
        // SIGTERM. This serves as a more obvious line of defense against the
        // boot proceeding past a required reboot.
        loop {
            thread::sleep(Duration::from_secs(5));
            info!("Still waiting for the host to be rebooted...");
        }
    } else {
        info!("No reboot required");
    }

    Ok(())
}

fn setup_logger(args: &Args) -> Result<()> {
    match args.subcommand {
        // Write the logs to a file while capturing dumps, since the journal isn't available
        Subcommand::CaptureDump(_) => {
            let log_file_path = Path::new(KDUMP_LOGS_PATH).join(LOG_FILE);
            let log_file = File::create(&log_file_path).context(error::WriteFileSnafu {
                path: log_file_path,
            })?;

            WriteLogger::init(args.log_level, LogConfig::default(), log_file)
                .context(error::LoggerSnafu)?;
        }
        // SimpleLogger will send errors to stderr and anything less to stdout.
        _ => {
            SimpleLogger::init(args.log_level, LogConfig::default()).context(error::LoggerSnafu)?
        }
    }

    Ok(())
}

fn run() -> Result<()> {
    let args: Args = argh::from_env();
    setup_logger(&args)?;

    match args.subcommand {
        Subcommand::CaptureDump(_) => capture_dump(),
        Subcommand::PrepareBoot(_) => prepare_boot(),
        Subcommand::LoadCrashKernel(_) => load_crash_kernel(),
        Subcommand::GenerateBootConfig(_) => generate_boot_config(args.config_path),
        Subcommand::GenerateBootSettings(_) => generate_boot_settings(),
        Subcommand::RebootIfRequired(_) => reboot_if_required(args.config_path),
    }
}

fn main() {
    if let Err(e) = run() {
        error!("{e}");
        process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::{boot_action, BootAction};
    use std::path::PathBuf;

    #[test]
    fn xbootldr_partition_on_the_disk_is_mounted() {
        let boot_partition_path = PathBuf::from("/dev/nvme0n1p2");

        assert_eq!(
            boot_action(Some(boot_partition_path.clone()), || panic!(
                "the image format should not be consulted when the disk has an XBOOTLDR partition"
            )),
            BootAction::MountXbootldr(boot_partition_path)
        );
    }

    #[test]
    fn uki_image_without_an_xbootldr_partition_fails() {
        assert_eq!(boot_action(None, || true), BootAction::MissingXbootldr);
    }

    #[test]
    fn grub_image_without_an_xbootldr_partition_uses_the_active_partition_set() {
        assert_eq!(boot_action(None, || false), BootAction::MountActiveSet);
    }
}
