[Unit]
# mount the plain-mode dm-crypt mapper opened by
# encrypt-unlock-private-fs.service instead of the raw partition.
After=encrypt-unlock-private-fs.service prepare-private-fs.service
Requires=prepare-private-fs.service

[Mount]
What=/dev/mapper/BOTTLEROCKET-PRIVATE
