[Service]
# wipe the fs signature of the data partition so that systemd-makefs recreates
# a fresh filesystem on every boot.
ExecStartPre=-/usr/sbin/wipefs --all --force ${DATA_PARTITION_BLOCK_DEVICE}
