[Service]
# With ephemeral-encryption-keys enabled, he DATA partition grow and the dm-crypt
# mapper resize are performed inside encrypt-unlock-local-fs.service. So, we override
# the systemd-repart operation with a no-op. We still let it run systemd-growfs on
# the mounted DATA partition /local
ExecStart=
ExecStart=/usr/bin/true
